sonar.projectKey=ajou-2026-1-capstone-5_ostone_ml
sonar.organization=ajou-2026-1-capstone-5
sonar.host.url=https://sonarcloud.io
sonar.sources=src/
sonar.exclusions=__pycache__/**,.venv/**,airflow/**,tests/**,**/*.pyc
sonar.coverage.exclusions=tests/**,**/__init__.py,**/conftest.py
sonar.python.coverage.reportPaths=coverage.xml