sonar.projectKey=ajou-2026-1-capstone-5_ostone_frontend
sonar.organization=ajou-2026-1-capstone-5
sonar.host.url=https://sonarcloud.io
sonar.sources=src/
sonar.exclusions=node_modules/**,dist/**,**/*.d.ts,**/coverage/**,**/lcov-report/**
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/mocks/**,**/test/**,**/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info