import type { WorkflowGraph } from "../../model/types";

/**
 * 풍부한 데모 그래프 — 모든 옵셔널 필드(description / iconHint / badges /
 * accentColor / meta / status / policyRef)를 채운 실전 시나리오.
 *
 * 시나리오: 카카오 채널로 들어온 상담을 등급별로 분기 처리하고,
 *           VIP 우선 처리 / 일반 회원 셀프 응대 / 비회원 리드 수집의 3-way 종착으로 마무리.
 */
export const enrichedDemoGraph: WorkflowGraph = {
  direction: "LR",
  nodes: [
    {
      id: "n1",
      type: "START",
      label: "상담이 인입되었을 때",
      description: "트리거 시점 · 최초 1회 — 연동 채널의 새 상담을 받아 워크플로우를 시작합니다.",
      iconHint: "Inbox",
      badges: ["트리거", "1회"],
      accentColor: "violet",
      meta: { channel: "kakao", trigger: "session.opened" },
      status: "COMPLETED",
      position: { x: 0, y: 220 },
    },
    {
      id: "n2",
      type: "DECISION",
      label: "고객 유형 분류하기",
      description: "고객 등급(customer.tier)에 따라 VIP / 일반 / 비회원 분기로 라우팅합니다.",
      iconHint: "GitBranch",
      badges: ["분기 3", "field:customer.tier"],
      accentColor: "amber",
      meta: { field: "customer.tier", branches: "3" },
      status: "COMPLETED",
      position: { x: 320, y: 220 },
    },
    {
      id: "n3",
      type: "ACTION",
      label: "VIP 등급 처리",
      description: "우선순위 높음으로 설정하고 상담 태그 VIP를 적용합니다.",
      policyRef: "PR-014",
      iconHint: "Zap",
      badges: ["tag:VIP", "priority:high"],
      accentColor: "indigo",
      meta: { tag: "VIP", priority: "high" },
      status: "ACTIVE",
      position: { x: 660, y: 40 },
    },
    {
      id: "n4",
      type: "ANSWER",
      label: "일반 회원 환영 메시지",
      description: "“[이름]님, 반가워요 😊 상담이 필요하신 주제를 선택해주세요.”",
      iconHint: "MessageSquare",
      badges: ["컨설팅 문의", "환불 안내"],
      accentColor: "sky",
      meta: { template: "welcome_member", buttons: "2" },
      status: "IDLE",
      position: { x: 660, y: 220 },
    },
    {
      id: "n5",
      type: "ACTION",
      label: "비회원 리드 제출받기",
      description: "이메일과 이름을 수집한 뒤 상담사 큐에 인계합니다.",
      policyRef: "LD-002",
      iconHint: "Zap",
      badges: ["form:email,name"],
      accentColor: "indigo",
      meta: { form: "lead_basic", consent: "required" },
      status: "FAILED",
      position: { x: 660, y: 400 },
    },
    {
      id: "n6",
      type: "HANDOFF",
      label: "VIP 전담 배정",
      description: "VIP 등급 상담을 전담 매니저 큐로 인계합니다. SLA 5분.",
      iconHint: "UserPlus",
      badges: ["팀: VIP 전담", "sla:5m"],
      accentColor: "rose",
      meta: { queue: "vip-managers", sla: "5m" },
      status: "IDLE",
      position: { x: 1000, y: 40 },
    },
    {
      id: "n7",
      type: "TERMINAL",
      label: "상담 종료",
      description: "self-served · 14:08",
      iconHint: "CircleCheck",
      accentColor: "zinc",
      meta: { outcome: "resolved", channel: "kakao" },
      status: "COMPLETED",
      position: { x: 1000, y: 220 },
    },
    {
      id: "n8",
      type: "HANDOFF",
      label: "상담사 연결",
      description: "리드 수집 후 일반 상담사 큐로 인계합니다.",
      iconHint: "UserPlus",
      badges: ["팀: 일반 상담"],
      accentColor: "rose",
      meta: { queue: "general-agents", sla: "10m" },
      status: "IDLE",
      position: { x: 1000, y: 400 },
    },
  ],
  edges: [
    { id: "e1", from: "n1", to: "n2" },
    { id: "e2", from: "n2", to: "n3", label: "VIP 일치" },
    { id: "e3", from: "n2", to: "n4", label: "일반 회원" },
    { id: "e4", from: "n2", to: "n5", label: "일치하지 않음" },
    { id: "e5", from: "n3", to: "n6" },
    { id: "e6", from: "n4", to: "n7" },
    { id: "e7", from: "n5", to: "n8", label: "retry × 3" },
  ],
};
