spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/init
    username: ${DB_USERNAME:init}
    password: ${DB_PASSWORD:init1234}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: DEBUG
    liquibase: DEBUG

airflow:
  webhook:
    secret: ${AIRFLOW_WEBHOOK_SECRET:local-airflow-webhook-secret}

storage:
  s3:
    bucket-name: init-raw-files-local
    region: us-east-1
    endpoint: http://localhost:9000
    access-key: ${MINIO_ROOT_USER:minioadmin}
    secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
    path-style-access: true
